[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"
viaIR = true
optimizer = true
optimizer_runs = 200 # or higher, e.g., 1000
# Explicitly ignore the old_reflax directory
ignored_error_codes = ["license", "code-size"]
fs_permissions = [{ access = "read", path = "./"}]
# Prevent compilation of files in old_reflax
skip = ["old_reflax/**"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.integration]
src = "src"
out = "out"
libs = ["lib"]
test = "test-integration"
solc = "0.8.13"
viaIR = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]
# Fork configuration will be provided via command line with -f flag

## Benchmark with different versions
#time forge build --solc 0.8.17
#time forge build --solc 0.8.21
#